name: Generate Org Stats & Activity Graphs

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-org-stats
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate 3D Contribution Calendar
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Generate 2D Activity Graph
        uses: maurodesouza/github-readme-activity-graph-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: profile-night-view.svg
          theme: github-dark
          area: true

      - name: Generate Snake Contribution Grid
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Deploy Output Assets to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
